package com.teamz.lab.debugger.utils

import android.app.ActivityManager
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.hardware.camera2.CameraCharacteristics
import android.hardware.camera2.CameraManager
import android.os.BatteryManager
import android.os.Build
import android.os.Environment
import android.os.PowerManager
import android.os.StatFs
import android.os.SystemClock
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

/**
 * Composes a compact plain-text prompt the user can paste into any AI chat
 * (Claude, ChatGPT, Gemini, Perplexity, etc.) to get instant, contextual help
 * about their phone. Zero setup — no MCP, no PIN, no config.
 *
 * Target length: <2000 chars so it fits in a single message input on any AI app.
 *
 * What this must NEVER include (policy line — same as [BridgeHttpServer]):
 *   - Any "quality / health / grade / score %" claim about camera or sensors
 *   - Any invented value we did not read from an API
 *
 * The prompt asks the AI to reply in plain language and to be honest about
 * uncertainty — mirrors the doc/AI_ONBOARDING_PROMPT.md rules.
 */
object AiShareTextGenerator {

    /**
     * Builds the text-prompt string. Reads Android APIs directly — no network,
     * no HTTP round-trip through the Bridge.
     *
     * Two shapes, discriminated by whether Bridge is on:
     *   - **Snapshot mode** (no bridgeUrl/bridgePin): the AI has no live channel,
     *     so we dump every metric we can read. This IS the AI's only data source.
     *   - **Live mode** (bridge on): the AI has the URL+PIN and can call
     *     `devicegpt_*` tools for fresh data any time. Sending the metric dump
     *     would (a) waste the AI's context, and (b) create a stale-vs-live trap
     *     where the AI reads a 10-min-old "100%" battery instead of calling the
     *     tool. So live mode sends only identity + the live handle + rules.
     */
    fun buildPrompt(context: Context, bridgeUrl: String? = null, bridgePin: String? = null): String {
        val liveMode = bridgeUrl != null && bridgePin != null
        return if (liveMode) buildLivePrompt(bridgeUrl!!, bridgePin!!)
        else buildSnapshotPrompt(context)
    }

    private fun buildSnapshotPrompt(context: Context): String {
        val ts = SimpleDateFormat("yyyy-MM-dd HH:mm z", Locale.US).apply {
            timeZone = TimeZone.getDefault()
        }.format(Date())

        val sb = StringBuilder(2048)
        sb.append("Please help me understand my Android phone. Here is a live snapshot as of ")
            .append(ts).append(".\n\n")

        sb.append("=== Device ===\n")
        sb.append("Model: ${Build.MANUFACTURER} ${Build.MODEL}\n")
        sb.append("Android: ${Build.VERSION.RELEASE} (SDK ${Build.VERSION.SDK_INT})\n")
        sb.append("Hardware: ${Build.HARDWARE}, board=${Build.BOARD}\n")
        sb.append("ABIs: ${Build.SUPPORTED_ABIS.joinToString(", ")}\n")

        sb.append("\n=== Battery ===\n")
        appendBattery(context, sb)

        sb.append("\n=== Storage ===\n")
        appendStorage(sb)

        sb.append("\n=== Memory ===\n")
        appendMemory(context, sb)

        sb.append("\n=== Network + WiFi ===\n")
        appendNetwork(context, sb)

        sb.append("\n=== Cameras (facts only, no quality score) ===\n")
        appendCameras(context, sb)

        sb.append("\n=== CPU + Thermal ===\n")
        appendCpu(sb)
        appendThermal(context, sb)

        sb.append("\n=== Uptime ===\n")
        val bootedAgoMs = SystemClock.elapsedRealtime()
        sb.append("Since last reboot: ").append(formatDuration(bootedAgoMs)).append("\n")

        appendBehaviorRules(sb, liveMode = false)
        appendCameraPlaybook(sb)

        sb.append("\n=== General ask ===\n")
        sb.append("Read the numbers above and tell me if anything looks unhealthy or unusual, ")
        sb.append("then end with one concrete next step I could try.\n")

        sb.append("\n(Snapshot generated by DeviceGPT for Android — not affiliated with any AI vendor.)\n")
        return sb.toString()
    }

    private fun buildLivePrompt(bridgeUrl: String, bridgePin: String): String {
        val sb = StringBuilder(1024)
        sb.append("Please help me with my Android phone. My DeviceGPT app is running a live bridge, ")
        sb.append("so you can read live phone data on demand — do not assume anything is static.\n\n")

        sb.append("=== Phone ===\n")
        sb.append("Model: ${Build.MANUFACTURER} ${Build.MODEL}\n")
        sb.append("Android: ${Build.VERSION.RELEASE} (SDK ${Build.VERSION.SDK_INT})\n")

        sb.append("\n=== Live access via MCP ===\n")
        sb.append("URL: ").append(bridgeUrl).append("\n")
        sb.append("PIN: ").append(bridgePin).append("\n")
        sb.append("Both change every session. Setup guide is in the DeviceGPT app under AI Bridge → ")
        sb.append("\"Set up live connection (advanced)\".\n")

        appendBehaviorRules(sb, liveMode = true)

        sb.append("\n=== General ask ===\n")
        sb.append("Ask me what I want help with, then use the `devicegpt_*` tools to answer with live data. ")
        sb.append("For camera problems: check permission first, then test hardware, then thermal, then storage, ")
        sb.append("then inspect an actual photo. Only suggest a repair shop if the hardware test or the photo shows a clear defect.\n")

        sb.append("\n(Prompt generated by DeviceGPT for Android — not affiliated with any AI vendor.)\n")
        return sb.toString()
    }

    /** Copies the prompt to the clipboard AND opens the system share chooser. */
    fun copyAndShare(context: Context, prompt: String) {
        val clip = context.getSystemService(Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
        clip.setPrimaryClip(android.content.ClipData.newPlainText("DeviceGPT AI prompt", prompt))
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, prompt)
            putExtra(Intent.EXTRA_SUBJECT, "My phone info — please help")
        }
        val chooser = Intent.createChooser(send, "Send to your AI").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(chooser)
    }

    // ─────────────────────── shared blocks ───────────────────────

    private fun appendBehaviorRules(sb: StringBuilder, liveMode: Boolean) {
        sb.append("\n=== How you should behave ===\n")
        if (liveMode) {
            sb.append("- FIRST: check if you have tools named `devicegpt_*` (like ")
            sb.append("`devicegpt_battery`, `devicegpt_capture_photo`). If yes, USE THEM ")
            sb.append("for anything I ask — the URL + PIN above wire you to live data, always fresh.\n")
            sb.append("- If you have no `devicegpt_*` tools, tell me so plainly and ask me to ")
            sb.append("paste a static snapshot instead. Do not guess.\n")
        } else {
            sb.append("- Work only from the numbers above. There is no live tool access in this share.\n")
            sb.append("- If I ask something not in the numbers above, tell me honestly you don't have it.\n")
        }
        sb.append("- Do NOT tell me which mode you are in unless I ask.\n")
        sb.append("- Plain, everyday language. Short sentences. No jargon my mum couldn't read.\n")
        sb.append("- Do NOT invent any value that is not in the data above")
        if (liveMode) sb.append(" (or a tool response)")
        sb.append(".\n")
        sb.append("- Do NOT rate the camera quality — that is not measurable from these APIs.\n")
        if (liveMode) {
            sb.append("- If a tool response has a `user_message` field, relay it VERBATIM. Do ")
            sb.append("not paraphrase or invent your own recovery step.\n")
            sb.append("- If a tool returns null or 'unknown', just say so — don't guess.\n")
        } else {
            sb.append("- If something is missing (a null or 'unknown'), just say so — don't guess.\n")
        }
    }

    private fun appendCameraPlaybook(sb: StringBuilder) {
        sb.append("\n=== If I say my camera is broken ===\n")
        sb.append("Follow this checklist IN ORDER, stop when you find the cause:\n")
        sb.append("  1. Ask which app is failing (Camera / WhatsApp / Zoom / etc.).\n")
        sb.append("  2. Check Camera permission for that app. If MCP: call ")
        sb.append("`devicegpt_permissions_status`. If not: tell me the exact fix path.\n")
        sb.append("  3. If MCP: call `devicegpt_test_camera_open` — see if hardware opens.\n")
        sb.append("  4. Check thermal state — camera auto-disables when hot.\n")
        sb.append("  5. If MCP: call `devicegpt_apps` — look for VPNs / privacy apps / ")
        sb.append("screen recorders that hijack the camera.\n")
        sb.append("  6. Check storage — a full disk can make camera refuse to save.\n")
        sb.append("  7. If MCP + steps 2-6 clear: ask me to Allow one `devicegpt_capture_photo`, ")
        sb.append("look at the actual picture (all black? green tint? blurry? dust spot?).\n")
        sb.append("  8. Only recommend a repair shop if step 3 or 7 shows a clear hardware signal. ")
        sb.append("Otherwise suggest force-close + clear cache + reinstall the app.\n")
    }

    // ─────────────────────── section builders ───────────────────────

    private fun appendBattery(context: Context, sb: StringBuilder) {
        val bm = context.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        val intent = context.registerReceiver(null, IntentFilter(Intent.ACTION_BATTERY_CHANGED))
        val pct = bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
        val temp = (intent?.getIntExtra(BatteryManager.EXTRA_TEMPERATURE, -1) ?: -1) / 10.0
        val volt = intent?.getIntExtra(BatteryManager.EXTRA_VOLTAGE, -1) ?: -1
        val status = intent?.getIntExtra(BatteryManager.EXTRA_STATUS, -1) ?: -1
        val plugged = intent?.getIntExtra(BatteryManager.EXTRA_PLUGGED, -1) ?: -1
        val healthCode = intent?.getIntExtra(BatteryManager.EXTRA_HEALTH, -1) ?: -1
        val plug = when (plugged) {
            BatteryManager.BATTERY_PLUGGED_AC -> "AC"
            BatteryManager.BATTERY_PLUGGED_USB -> "USB"
            BatteryManager.BATTERY_PLUGGED_WIRELESS -> "wireless"
            else -> "unplugged"
        }
        val charging = status == BatteryManager.BATTERY_STATUS_CHARGING || status == BatteryManager.BATTERY_STATUS_FULL
        val health = when (healthCode) {
            BatteryManager.BATTERY_HEALTH_GOOD -> "good"
            BatteryManager.BATTERY_HEALTH_OVERHEAT -> "overheat"
            BatteryManager.BATTERY_HEALTH_DEAD -> "dead"
            BatteryManager.BATTERY_HEALTH_OVER_VOLTAGE -> "over_voltage"
            BatteryManager.BATTERY_HEALTH_UNSPECIFIED_FAILURE -> "unspecified_failure"
            BatteryManager.BATTERY_HEALTH_COLD -> "cold"
            else -> "unknown"
        }
        sb.append("Level: ${pct}%\n")
        sb.append("Charging: ${if (charging) "yes" else "no"} ($plug)\n")
        if (temp > 0) sb.append("Temperature: ${"%.1f".format(temp)} °C\n")
        if (volt > 0) sb.append("Voltage: $volt mV\n")
        sb.append("Reported health: $health\n")
    }

    private fun appendStorage(sb: StringBuilder) {
        val st = StatFs(Environment.getDataDirectory().path)
        val total = st.blockCountLong * st.blockSizeLong
        val free = st.availableBlocksLong * st.blockSizeLong
        val used = total - free
        val pctUsed = if (total > 0) (used * 100.0 / total) else 0.0
        sb.append("Internal total: ${bytesToGb(total)} GB\n")
        sb.append("Internal free: ${bytesToGb(free)} GB\n")
        sb.append("Used: ${"%.1f".format(pctUsed)}%\n")
    }

    private fun appendMemory(context: Context, sb: StringBuilder) {
        val am = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val info = ActivityManager.MemoryInfo()
        am.getMemoryInfo(info)
        sb.append("Total RAM: ${bytesToGb(info.totalMem)} GB\n")
        sb.append("Available RAM: ${bytesToGb(info.availMem)} GB\n")
        sb.append("Low-memory state: ${if (info.lowMemory) "YES (OS is under memory pressure)" else "no"}\n")
    }

    private fun appendNetwork(context: Context, sb: StringBuilder) {
        val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as android.net.ConnectivityManager
        val active = cm.activeNetwork
        val caps = active?.let { cm.getNetworkCapabilities(it) }
        val isWifi = caps?.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI) == true
        val isCell = caps?.hasTransport(android.net.NetworkCapabilities.TRANSPORT_CELLULAR) == true
        val hasNet = caps?.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_VALIDATED) == true
        val lanIp = LanIpResolver.getLanIpv4() ?: "not on WiFi"
        sb.append("Transport: ${if (isWifi) "WiFi" else if (isCell) "cellular" else "none/off"}\n")
        sb.append("Internet reachable: ${if (hasNet) "yes" else "no"}\n")
        sb.append("LAN IPv4: $lanIp\n")
    }

    private fun appendCameras(context: Context, sb: StringBuilder) {
        try {
            val cm = context.getSystemService(Context.CAMERA_SERVICE) as CameraManager
            val ids = cm.cameraIdList
            sb.append("Third-party-visible lens count: ${ids.size}\n")
            for (id in ids) {
                val c = cm.getCameraCharacteristics(id)
                val facing = when (c.get(CameraCharacteristics.LENS_FACING)) {
                    CameraCharacteristics.LENS_FACING_FRONT -> "front"
                    CameraCharacteristics.LENS_FACING_BACK -> "back"
                    CameraCharacteristics.LENS_FACING_EXTERNAL -> "external"
                    else -> "unknown"
                }
                val focals = c.get(CameraCharacteristics.LENS_INFO_AVAILABLE_FOCAL_LENGTHS)?.joinToString(", ") { "${it}mm" } ?: "?"
                val hasFlash = c.get(CameraCharacteristics.FLASH_INFO_AVAILABLE) ?: false
                sb.append("- Lens $id: $facing, focal $focals, flash=${if (hasFlash) "yes" else "no"}\n")
            }
        } catch (e: Exception) {
            sb.append("(camera info unavailable: ${e.message})\n")
        }
    }

    private fun appendCpu(sb: StringBuilder) {
        sb.append("CPU cores: ${Runtime.getRuntime().availableProcessors()}\n")
        val maxKhz = try {
            java.io.File("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq").readText().trim().toLongOrNull()
        } catch (e: Exception) { null }
        if (maxKhz != null) sb.append("Core 0 max freq: ${"%.2f".format(maxKhz / 1_000_000.0)} GHz\n")
    }

    private fun appendThermal(context: Context, sb: StringBuilder) {
        if (Build.VERSION.SDK_INT < 29) {
            sb.append("Thermal state: unavailable (Android <10)\n")
            return
        }
        val pm = context.getSystemService(Context.POWER_SERVICE) as PowerManager
        val name = when (pm.currentThermalStatus) {
            PowerManager.THERMAL_STATUS_NONE -> "none (normal)"
            PowerManager.THERMAL_STATUS_LIGHT -> "light (warm)"
            PowerManager.THERMAL_STATUS_MODERATE -> "moderate (throttling starting)"
            PowerManager.THERMAL_STATUS_SEVERE -> "severe (heavy throttling)"
            PowerManager.THERMAL_STATUS_CRITICAL -> "critical (near-shutdown)"
            PowerManager.THERMAL_STATUS_EMERGENCY -> "emergency"
            PowerManager.THERMAL_STATUS_SHUTDOWN -> "shutdown imminent"
            else -> "unknown"
        }
        sb.append("Thermal state: $name\n")
        if (pm.isPowerSaveMode) sb.append("Power-save mode: ON\n")
        if (pm.isDeviceIdleMode) sb.append("Device idle (doze) mode: ON\n")
    }

    // ─────────────────────── helpers ───────────────────────

    private fun bytesToGb(bytes: Long): String = "%.2f".format(bytes / 1_073_741_824.0)

    private fun formatDuration(ms: Long): String {
        val totalSec = ms / 1000
        val d = totalSec / 86400
        val h = (totalSec % 86400) / 3600
        val m = (totalSec % 3600) / 60
        return buildString {
            if (d > 0) append("${d}d ")
            if (h > 0 || d > 0) append("${h}h ")
            append("${m}m")
        }
    }
}
